# Generated by Django 4.0.5 on 2022-06-18 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='normalcustomerprofile',
            name='ephemeral_key',
        ),
    ]
