# Generated by Django 4.0.5 on 2022-06-12 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='track_duration',
            field=models.CharField(max_length=8),
        ),
    ]
