# Generated by Django 4.0.5 on 2022-06-12 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_alter_song_track_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='track_duration',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
