# Generated by Django 4.0.5 on 2022-06-14 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_alter_song_track_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='price',
            field=models.DecimalField(decimal_places=2, default=9.99, max_digits=6),
            preserve_default=False,
        ),
    ]
