# Generated by Django 4.0.5 on 2022-06-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_artist',
            field=models.BooleanField(default=False),
        ),
    ]
